using System;
using System.Security.Cryptography.X509Certificates;
using cpu6502.Interfaces;

namespace cpu6502
{
	public class InstructionSet
	{
        private Cpu cpu;
        public OpCode[] Ops;
        //public Dictionary<byte, OpCode> Ops;

        
        public InstructionSet(Cpu cpu)
        {

            // check these .. something is wrong here (we had 2 0x09's
            this.cpu = cpu;

            this.Ops = new OpCode[] {
                new OpCode { name = "BRK", op = cpu.BRK, am = cpu.IMM, cycles = 7 }, new OpCode { name = "ORA", op = cpu.ORA, am = cpu.IZX, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 8 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 3 }, new OpCode { name = "ORA", op = cpu.ORA, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "ASL", op = cpu.ASL, am = cpu.ZP0, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 5 }, new OpCode { name = "PHP", op = cpu.PHP, am = cpu.IMP, cycles = 3 }, new OpCode { name = "ORA", op = cpu.ORA, am = cpu.IMM, cycles = 2 }, new OpCode { name = "ASL", op = cpu.ASL, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "ORA", op = cpu.ORA, am = cpu.ABS, cycles = 4 }, new OpCode { name = "ASL", op = cpu.ASL, am = cpu.ABS, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 },
                new OpCode { name = "BPL", op = cpu.BPL, am = cpu.REL, cycles = 2 }, new OpCode { name = "ORA", op = cpu.ORA, am = cpu.IZY, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 8 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "ORA", op = cpu.ORA, am = cpu.ZPX, cycles = 4 }, new OpCode { name = "ASL", op = cpu.ASL, am = cpu.ZPX, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 }, new OpCode { name = "CLC", op = cpu.CLC, am = cpu.IMP, cycles = 2 }, new OpCode { name = "ORA", op = cpu.ORA, am = cpu.ABY, cycles = 4 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 7 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "ORA", op = cpu.ORA, am = cpu.ABX, cycles = 4 }, new OpCode { name = "ASL", op = cpu.ASL, am = cpu.ABX, cycles = 7 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 7 },
                new OpCode { name = "JSR", op = cpu.JSR, am = cpu.ABS, cycles = 6 }, new OpCode { name = "AND", op = cpu.AND, am = cpu.IZX, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 8 }, new OpCode { name = "BIT", op = cpu.BIT, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "AND", op = cpu.AND, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "ROL", op = cpu.ROL, am = cpu.ZP0, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 5 }, new OpCode { name = "PLP", op = cpu.PLP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "AND", op = cpu.AND, am = cpu.IMM, cycles = 2 }, new OpCode { name = "ROL", op = cpu.ROL, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "BIT", op = cpu.BIT, am = cpu.ABS, cycles = 4 }, new OpCode { name = "AND", op = cpu.AND, am = cpu.ABS, cycles = 4 }, new OpCode { name = "ROL", op = cpu.ROL, am = cpu.ABS, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 },
                new OpCode { name = "BMI", op = cpu.BMI, am = cpu.REL, cycles = 2 }, new OpCode { name = "AND", op = cpu.AND, am = cpu.IZY, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 8 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "AND", op = cpu.AND, am = cpu.ZPX, cycles = 4 }, new OpCode { name = "ROL", op = cpu.ROL, am = cpu.ZPX, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 }, new OpCode { name = "SEC", op = cpu.SEC, am = cpu.IMP, cycles = 2 }, new OpCode { name = "AND", op = cpu.AND, am = cpu.ABY, cycles = 4 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 7 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "AND", op = cpu.AND, am = cpu.ABX, cycles = 4 }, new OpCode { name = "ROL", op = cpu.ROL, am = cpu.ABX, cycles = 7 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 7 },
                new OpCode { name = "RTI", op = cpu.RTI, am = cpu.IMP, cycles = 6 }, new OpCode { name = "EOR", op = cpu.EOR, am = cpu.IZX, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 8 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 3 }, new OpCode { name = "EOR", op = cpu.EOR, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "LSR", op = cpu.LSR, am = cpu.ZP0, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 5 }, new OpCode { name = "PHA", op = cpu.PHA, am = cpu.IMP, cycles = 3 }, new OpCode { name = "EOR", op = cpu.EOR, am = cpu.IMM, cycles = 2 }, new OpCode { name = "LSR", op = cpu.LSR, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "JMP", op = cpu.JMP, am = cpu.ABS, cycles = 3 }, new OpCode { name = "EOR", op = cpu.EOR, am = cpu.ABS, cycles = 4 }, new OpCode { name = "LSR", op = cpu.LSR, am = cpu.ABS, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 },
                new OpCode { name = "BVC", op = cpu.BVC, am = cpu.REL, cycles = 2 }, new OpCode { name = "EOR", op = cpu.EOR, am = cpu.IZY, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 8 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "EOR", op = cpu.EOR, am = cpu.ZPX, cycles = 4 }, new OpCode { name = "LSR", op = cpu.LSR, am = cpu.ZPX, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 }, new OpCode { name = "CLI", op = cpu.CLI, am = cpu.IMP, cycles = 2 }, new OpCode { name = "EOR", op = cpu.EOR, am = cpu.ABY, cycles = 4 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 7 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "EOR", op = cpu.EOR, am = cpu.ABX, cycles = 4 }, new OpCode { name = "LSR", op = cpu.LSR, am = cpu.ABX, cycles = 7 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 7 },
                new OpCode { name = "RTS", op = cpu.RTS, am = cpu.IMP, cycles = 6 }, new OpCode { name = "ADC", op = cpu.ADC, am = cpu.IZX, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 8 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 3 }, new OpCode { name = "ADC", op = cpu.ADC, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "ROR", op = cpu.ROR, am = cpu.ZP0, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 5 }, new OpCode { name = "PLA", op = cpu.PLA, am = cpu.IMP, cycles = 4 }, new OpCode { name = "ADC", op = cpu.ADC, am = cpu.IMM, cycles = 2 }, new OpCode { name = "ROR", op = cpu.ROR, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "JMP", op = cpu.JMP, am = cpu.IND, cycles = 5 }, new OpCode { name = "ADC", op = cpu.ADC, am = cpu.ABS, cycles = 4 }, new OpCode { name = "ROR", op = cpu.ROR, am = cpu.ABS, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 },
                new OpCode { name = "BVS", op = cpu.BVS, am = cpu.REL, cycles = 2 }, new OpCode { name = "ADC", op = cpu.ADC, am = cpu.IZY, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 8 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "ADC", op = cpu.ADC, am = cpu.ZPX, cycles = 4 }, new OpCode { name = "ROR", op = cpu.ROR, am = cpu.ZPX, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 }, new OpCode { name = "SEI", op = cpu.SEI, am = cpu.IMP, cycles = 2 }, new OpCode { name = "ADC", op = cpu.ADC, am = cpu.ABY, cycles = 4 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 7 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "ADC", op = cpu.ADC, am = cpu.ABX, cycles = 4 }, new OpCode { name = "ROR", op = cpu.ROR, am = cpu.ABX, cycles = 7 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 7 },
                new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 2 }, new OpCode { name = "STA", op = cpu.STA, am = cpu.IZX, cycles = 6 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 }, new OpCode { name = "STY", op = cpu.STY, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "STA", op = cpu.STA, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "STX", op = cpu.STX, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 3 }, new OpCode { name = "DEY", op = cpu.DEY, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 2 }, new OpCode { name = "TXA", op = cpu.TXA, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "STY", op = cpu.STY, am = cpu.ABS, cycles = 4 }, new OpCode { name = "STA", op = cpu.STA, am = cpu.ABS, cycles = 4 }, new OpCode { name = "STX", op = cpu.STX, am = cpu.ABS, cycles = 4 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 4 },
                new OpCode { name = "BCC", op = cpu.BCC, am = cpu.REL, cycles = 2 }, new OpCode { name = "STA", op = cpu.STA, am = cpu.IZY, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 }, new OpCode { name = "STY", op = cpu.STY, am = cpu.ZPX, cycles = 4 }, new OpCode { name = "STA", op = cpu.STA, am = cpu.ZPX, cycles = 4 }, new OpCode { name = "STX", op = cpu.STX, am = cpu.ZPY, cycles = 4 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 4 }, new OpCode { name = "TYA", op = cpu.TYA, am = cpu.IMP, cycles = 2 }, new OpCode { name = "STA", op = cpu.STA, am = cpu.ABY, cycles = 5 }, new OpCode { name = "TXS", op = cpu.TXS, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 5 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 5 }, new OpCode { name = "STA", op = cpu.STA, am = cpu.ABX, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 5 },
                new OpCode { name = "LDY", op = cpu.LDY, am = cpu.IMM, cycles = 2 }, new OpCode { name = "LDA", op = cpu.LDA, am = cpu.IZX, cycles = 6 }, new OpCode { name = "LDX", op = cpu.LDX, am = cpu.IMM, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 }, new OpCode { name = "LDY", op = cpu.LDY, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "LDA", op = cpu.LDA, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "LDX", op = cpu.LDX, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 3 }, new OpCode { name = "TAY", op = cpu.TAY, am = cpu.IMP, cycles = 2 }, new OpCode { name = "LDA", op = cpu.LDA, am = cpu.IMM, cycles = 2 }, new OpCode { name = "TAX", op = cpu.TAX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "LDY", op = cpu.LDY, am = cpu.ABS, cycles = 4 }, new OpCode { name = "LDA", op = cpu.LDA, am = cpu.ABS, cycles = 4 }, new OpCode { name = "LDX", op = cpu.LDX, am = cpu.ABS, cycles = 4 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 4 },
                new OpCode { name = "BCS", op = cpu.BCS, am = cpu.REL, cycles = 2 }, new OpCode { name = "LDA", op = cpu.LDA, am = cpu.IZY, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 5 }, new OpCode { name = "LDY", op = cpu.LDY, am = cpu.ZPX, cycles = 4 }, new OpCode { name = "LDA", op = cpu.LDA, am = cpu.ZPX, cycles = 4 }, new OpCode { name = "LDX", op = cpu.LDX, am = cpu.ZPY, cycles = 4 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 4 }, new OpCode { name = "CLV", op = cpu.CLV, am = cpu.IMP, cycles = 2 }, new OpCode { name = "LDA", op = cpu.LDA, am = cpu.ABY, cycles = 4 }, new OpCode { name = "TSX", op = cpu.TSX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 4 }, new OpCode { name = "LDY", op = cpu.LDY, am = cpu.ABX, cycles = 4 }, new OpCode { name = "LDA", op = cpu.LDA, am = cpu.ABX, cycles = 4 }, new OpCode { name = "LDX", op = cpu.LDX, am = cpu.ABY, cycles = 4 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 4 },
                new OpCode { name = "CPY", op = cpu.CPY, am = cpu.IMM, cycles = 2 }, new OpCode { name = "CMP", op = cpu.CMP, am = cpu.IZX, cycles = 6 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 8 }, new OpCode { name = "CPY", op = cpu.CPY, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "CMP", op = cpu.CMP, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "DEC", op = cpu.DEC, am = cpu.ZP0, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 5 }, new OpCode { name = "INY", op = cpu.INY, am = cpu.IMP, cycles = 2 }, new OpCode { name = "CMP", op = cpu.CMP, am = cpu.IMM, cycles = 2 }, new OpCode { name = "DEX", op = cpu.DEX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "CPY", op = cpu.CPY, am = cpu.ABS, cycles = 4 }, new OpCode { name = "CMP", op = cpu.CMP, am = cpu.ABS, cycles = 4 }, new OpCode { name = "DEC", op = cpu.DEC, am = cpu.ABS, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 },
                new OpCode { name = "BNE", op = cpu.BNE, am = cpu.REL, cycles = 2 }, new OpCode { name = "CMP", op = cpu.CMP, am = cpu.IZY, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 8 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "CMP", op = cpu.CMP, am = cpu.ZPX, cycles = 4 }, new OpCode { name = "DEC", op = cpu.DEC, am = cpu.ZPX, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 }, new OpCode { name = "CLD", op = cpu.CLD, am = cpu.IMP, cycles = 2 }, new OpCode { name = "CMP", op = cpu.CMP, am = cpu.ABY, cycles = 4 }, new OpCode { name = "NOP", op = cpu.NOP, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 7 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "CMP", op = cpu.CMP, am = cpu.ABX, cycles = 4 }, new OpCode { name = "DEC", op = cpu.DEC, am = cpu.ABX, cycles = 7 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 7 },
                new OpCode { name = "CPX", op = cpu.CPX, am = cpu.IMM, cycles = 2 }, new OpCode { name = "SBC", op = cpu.SBC, am = cpu.IZX, cycles = 6 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 8 }, new OpCode { name = "CPX", op = cpu.CPX, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "SBC", op = cpu.SBC, am = cpu.ZP0, cycles = 3 }, new OpCode { name = "INC", op = cpu.INC, am = cpu.ZP0, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 5 }, new OpCode { name = "INX", op = cpu.INX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "SBC", op = cpu.SBC, am = cpu.IMM, cycles = 2 }, new OpCode { name = "NOP", op = cpu.NOP, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.SBC, am = cpu.IMP, cycles = 2 }, new OpCode { name = "CPX", op = cpu.CPX, am = cpu.ABS, cycles = 4 }, new OpCode { name = "SBC", op = cpu.SBC, am = cpu.ABS, cycles = 4 }, new OpCode { name = "INC", op = cpu.INC, am = cpu.ABS, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 },
                new OpCode { name = "BEQ", op = cpu.BEQ, am = cpu.REL, cycles = 2 }, new OpCode { name = "SBC", op = cpu.SBC, am = cpu.IZY, cycles = 5 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 8 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "SBC", op = cpu.SBC, am = cpu.ZPX, cycles = 4 }, new OpCode { name = "INC", op = cpu.INC, am = cpu.ZPX, cycles = 6 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 6 }, new OpCode { name = "SED", op = cpu.SED, am = cpu.IMP, cycles = 2 }, new OpCode { name = "SBC", op = cpu.SBC, am = cpu.ABY, cycles = 4 }, new OpCode { name = "NOP", op = cpu.NOP, am = cpu.IMP, cycles = 2 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 7 }, new OpCode { name = "???", op = cpu.NOP, am = cpu.IMP, cycles = 4 }, new OpCode { name = "SBC", op = cpu.SBC, am = cpu.ABX, cycles = 4 }, new OpCode { name = "INC", op = cpu.INC, am = cpu.ABX, cycles = 7 }, new OpCode { name = "???", op = cpu.XXX, am = cpu.IMP, cycles = 7 },
               
            };

            for(int oc = 0; oc<=255; oc++)
                Ops[oc].opcode = (byte)oc;

        }
    
   
    }
}

